apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-server
  name: web-server
spec:
  selector:
    app: web-server
  type: NodePort
  ports:
  - port: 40051
    nodePort: 30000
    protocol: TCP
