# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_stream.proto\x12\x0b\x64\x61ta_stream\"\xca\x01\n\x04Game\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\x11\n\tdeveloper\x18\x03 \x01(\t\x12\x11\n\tpublisher\x18\x04 \x01(\t\x12\r\n\x05genre\x18\x05 \x01(\t\x12\x13\n\x0breleaseDate\x18\x06 \x01(\t\x12\x16\n\x0e\x63riticPositive\x18\x07 \x01(\x05\x12\x15\n\rcriticNeutral\x18\x08 \x01(\x05\x12\x16\n\x0e\x63riticNegative\x18\t \x01(\x05\x12\x11\n\tmetascore\x18\n \x01(\x05\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xa4\x01\n\x0c\x41nalysedData\x12\x11\n\tanalytic1\x18\x01 \x03(\x05\x12\x11\n\tanalytic2\x18\x02 \x03(\t\x12\x11\n\tanalytic3\x18\x03 \x03(\t\x12\x11\n\tanalytic4\x18\x04 \x03(\x05\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x12\n\nanalytic4a\x18\x06 \x03(\x05\x12\x12\n\nanalytic4b\x18\x07 \x03(\x05\x12\x12\n\nanalytic4c\x18\x08 \x03(\x05\x32\xda\x01\n\ndataStream\x12@\n\x0cListFeatures\x12\x19.data_stream.HelloRequest\x1a\x11.data_stream.Game\"\x00\x30\x01\x12@\n\x0cSendFeatures\x12\x11.data_stream.Game\x1a\x19.data_stream.HelloRequest\"\x00(\x01\x12H\n\x0eSendOneFeature\x12\x19.data_stream.AnalysedData\x1a\x19.data_stream.HelloRequest\"\x00\x62\x06proto3')



_GAME = DESCRIPTOR.message_types_by_name['Game']
_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_ANALYSEDDATA = DESCRIPTOR.message_types_by_name['AnalysedData']
Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'data_stream_pb2'
  # @@protoc_insertion_point(class_scope:data_stream.Game)
  })
_sym_db.RegisterMessage(Game)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'data_stream_pb2'
  # @@protoc_insertion_point(class_scope:data_stream.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

AnalysedData = _reflection.GeneratedProtocolMessageType('AnalysedData', (_message.Message,), {
  'DESCRIPTOR' : _ANALYSEDDATA,
  '__module__' : 'data_stream_pb2'
  # @@protoc_insertion_point(class_scope:data_stream.AnalysedData)
  })
_sym_db.RegisterMessage(AnalysedData)

_DATASTREAM = DESCRIPTOR.services_by_name['dataStream']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAME._serialized_start=35
  _GAME._serialized_end=237
  _HELLOREQUEST._serialized_start=239
  _HELLOREQUEST._serialized_end=267
  _ANALYSEDDATA._serialized_start=270
  _ANALYSEDDATA._serialized_end=434
  _DATASTREAM._serialized_start=437
  _DATASTREAM._serialized_end=655
# @@protoc_insertion_point(module_scope)
