# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_stream2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_stream2.proto\x12\x0c\x64\x61ta_stream2\"\xc0\x01\n\tGameSales\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\x13\n\x0breleaseYear\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\x12\x14\n\x0c\x61mericaSales\x18\x05 \x01(\x02\x12\x0f\n\x07\x65uSales\x18\x06 \x01(\x02\x12\x0f\n\x07jpSales\x18\x07 \x01(\x02\x12\x12\n\notherSales\x18\x08 \x01(\x02\x12\x13\n\x0bglobalSales\x18\t \x01(\x02\x12\x0e\n\x06rating\x18\n \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"|\n\x0c\x41nalysedData\x12\x11\n\tanalytic1\x18\x01 \x01(\x02\x12\x11\n\tanalytic2\x18\x02 \x03(\x02\x12\x11\n\tanalytic3\x18\x03 \x03(\t\x12\x11\n\tanalytic4\x18\x04 \x03(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x12\n\nanalytic2b\x18\x06 \x01(\x02\x32\xeb\x01\n\x0b\x64\x61taStream2\x12G\n\x0cListFeatures\x12\x1a.data_stream2.HelloRequest\x1a\x17.data_stream2.GameSales\"\x00\x30\x01\x12G\n\x0cSendFeatures\x12\x17.data_stream2.GameSales\x1a\x1a.data_stream2.HelloRequest\"\x00(\x01\x12J\n\x0eSendOneFeature\x12\x1a.data_stream2.AnalysedData\x1a\x1a.data_stream2.HelloRequest\"\x00\x62\x06proto3')



_GAMESALES = DESCRIPTOR.message_types_by_name['GameSales']
_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_ANALYSEDDATA = DESCRIPTOR.message_types_by_name['AnalysedData']
GameSales = _reflection.GeneratedProtocolMessageType('GameSales', (_message.Message,), {
  'DESCRIPTOR' : _GAMESALES,
  '__module__' : 'data_stream2_pb2'
  # @@protoc_insertion_point(class_scope:data_stream2.GameSales)
  })
_sym_db.RegisterMessage(GameSales)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'data_stream2_pb2'
  # @@protoc_insertion_point(class_scope:data_stream2.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

AnalysedData = _reflection.GeneratedProtocolMessageType('AnalysedData', (_message.Message,), {
  'DESCRIPTOR' : _ANALYSEDDATA,
  '__module__' : 'data_stream2_pb2'
  # @@protoc_insertion_point(class_scope:data_stream2.AnalysedData)
  })
_sym_db.RegisterMessage(AnalysedData)

_DATASTREAM2 = DESCRIPTOR.services_by_name['dataStream2']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMESALES._serialized_start=37
  _GAMESALES._serialized_end=229
  _HELLOREQUEST._serialized_start=231
  _HELLOREQUEST._serialized_end=259
  _ANALYSEDDATA._serialized_start=261
  _ANALYSEDDATA._serialized_end=385
  _DATASTREAM2._serialized_start=388
  _DATASTREAM2._serialized_end=623
# @@protoc_insertion_point(module_scope)
